# Generated by Django 3.1.5 on 2021-05-05 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcomment',
            name='confirmed',
        ),
    ]
