# Generated by Django 3.1.5 on 2021-05-11 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_projectcomment_confirmed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectComment',
        ),
    ]
